sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sinusen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sinusen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-776833476431"
  bucket_path: "docker"
  on:
    branch: master
  access-key-id: "$AWS_ACCESS_KEY"
  secret-access-key: "$AWS_SECRET_KEY"
  