sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t sinusen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sinusen/docker-react npm run test -- --coverage